# Generated by Django 4.2.2 on 2023-07-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
