# Generated by Django 4.2.2 on 2023-07-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
