# Generated by Django 4.2.2 on 2023-07-05 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
