# Generated by Django 4.2.2 on 2023-07-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_zip_code_alter_address_number'),
        ('users', '0002_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='addresses.address'),
        ),
    ]
