# Generated by Django 4.2.2 on 2023-07-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('XBOX', 'Xbox'), ('PLAYSTATION', 'Playstation'), ('PC', 'Pc'), ('INDEFINIDO', 'Default')], default='INDEFINIDO', max_length=12)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
